### ISSUE TITLE
Local variable error

### ISSUE THREAD

**Issue by pachax001** [Prudhvi-pln/udb#6]
2023-10-22 16:24:32,822 - INFO - <module>:211 - -------------------------------- NEW UDB INSTANCE v2.10.2 --------------------------------
2023-10-22 16:24:32,822 - INFO - <module>:213 - CLI options: config_file = 'config_udb.yaml', series_type_predef = None, series_name_predef = None, series_year_predef = None, episodes_pred>
2023-10-22 16:24:33,704 - INFO - <module>:217 - Selected Series type: drama
2023-10-22 16:24:33,704 - INFO - <module>:226 - Client: <Clients.DramaClient.DramaClient object at 0xffff91b67be0>
2023-10-22 16:24:37,969 - INFO - search_and_select_series:50 - Searching with keyword: arthdal
2023-10-22 16:24:40,624 - INFO - <module>:254 - Selected series: {'title': 'Arthdal Chronicles: The Sword of Aramun (2023)', 'link': 'https://myasiantv.ac//show/arthdal-chronicles-season-2>
2023-10-22 16:24:40,624 - INFO - <module>:257 - Fetching episodes list
2023-10-22 16:24:41,156 - INFO - <module>:262 - Displaying episodes list
2023-10-22 16:24:43,204 - INFO - <module>:283 - Fetching episodes between ep_start = 12.0 and ep_end = 12.0
2023-10-22 16:24:45,400 - ERROR - _send_request:71 - Failed with response code: 500
2023-10-22 16:24:47,843 - ERROR - _send_request:71 - Failed with response code: 500
2023-10-22 16:24:52,282 - ERROR - _send_request:71 - Failed with response code: 500
2023-10-22 16:25:00,730 - ERROR - _send_request:71 - Failed with response code: 500
2023-10-22 16:25:00,730 - WARNING - _get_download_links:227 - Failed to fetch m3u8 links from dlink = 'https://main.a387e6278d8e06083d813358762e0ac63.com/stream/a6226a4838885b3bfeca3827200>
2023-10-22 16:25:00,730 - WARNING - _get_download_links:229 - No other alternatives found
2023-10-22 16:25:12,637 - INFO - <module>:322 - Selected download resolution: 480
2023-10-22 16:25:12,637 - INFO - <module>:325 - Fetching m3u8 links for selected episodes
2023-10-22 16:25:12,638 - ERROR - <module>:360 - Error occurred: local variable 'resolution' referenced before assignment. Check log for more details.
2023-10-22 16:25:12,638 - WARNING - <module>:361 - Stacktrace: Traceback (most recent call last):
  File "/home/ubuntu/udb/udb.py", line 327, in <module>
    target_dl_links = client.fetch_m3u8_links(target_ep_links, resolution, episode_prefix)
  File "/home/ubuntu/udb/Clients/DramaClient.py", line 365, in fetch_m3u8_links
    selected_resolution = self._resolution_selector(link.keys(), resolution, self.selector_strategy)
  File "/home/ubuntu/udb/Clients/BaseClient.py", line 205, in _resolution_selector
    return resolution      # return lowest resolution if reached start of loop
UnboundLocalError: local variable 'resolution' referenced before assignment
Also resolutins are not showing

**Comment by Prudhvi-pln** [comment]
I tried running it for same series, and it is working as expected:
<img width="659" alt="image" src="https://github.com/Prudhvi-pln/udb/assets/62585477/93e0e7f2-d319-445a-a1c8-8c59e7c0e06d">

Probably the links are not updated when you accessed. Please check now.
Could not re-create the issue. Please let me know if similar issue occurs. I'll try to look into it asap.
